[package]
name = "spec_freeze"
version = "0.1.0"
authors = ["Lorenzo Panieri <panierilorenzo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfft = "4.0.0"
vst = "0.2.1"
itertools = "0.9.0"

[lib]
name = "SPEC_FREEZE"
crate-type = ["cdylib"]